const { Schema, model } = require('mongoose')

var hidroplantSchema = new Schema({
    name: String,
    db_status: String,
    country: String,
    iso: String,
    reservoir: String,
    lake: String,
    purpose: String,
    admin_unit: String,
    owner: String,
    near_city: String,
    district: String,
    river: String,
    main_basin: String,
    catch_area: String,
    op_status: String,
    commisioned: String,
    dam_completed: Number,
    no_units: String,
    dam_heigth: Number,
    min_wHeadHgt: Number,
    max_wHeadHgt: Number,
    res_capacity: Number,
    res_area: Number,
    elec_cap: Number,
    transm_exist: String,
    transm_length: Number,
    transm_planned: Number,
    type: String,
    ann_firm_gen: Number,
    ann_total_gen: Number,
    lat_res: Number,
    long_res: Number,
    lat_hp1: Number,
    long_hp1: Number,
    lat_hp2: Number,
    long_hp2: Number,
    display: String,
})

module.exports = model('Hidroplant', hidroplantSchema, 'Hidroplant')